// <auto-generated />
namespace Care_UP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class attendant_edit0930 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attendant_edit0930));
        
        string IMigrationMetadata.Id
        {
            get { return "202009030226089_attendant_edit0930"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
