// <auto-generated />
namespace Care_UP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 移除order的starttime問號移除detaildate新增carerecord欄位remark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(移除order的starttime問號移除detaildate新增carerecord欄位remark));
        
        string IMigrationMetadata.Id
        {
            get { return "202009140232509_移除order的starttime問號移除detaildate新增carerecord欄位remark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
