// <auto-generated />
namespace Care_UP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 因應列舉改動 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(因應列舉改動));
        
        string IMigrationMetadata.Id
        {
            get { return "202009170604306_因應列舉改動"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
