// <auto-generated />
namespace Care_UP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 訂單的startTimeendTime不要問號 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(訂單的startTimeendTime不要問號));
        
        string IMigrationMetadata.Id
        {
            get { return "202009110548548_訂單的startTimeendTime不要問號"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
