// <auto-generated />
namespace Care_UP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class attendeant_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attendeant_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "202009020545061_attendeant_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
