// <auto-generated />
namespace Care_UP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 增加QA用的資料表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(增加QA用的資料表));
        
        string IMigrationMetadata.Id
        {
            get { return "202009150842351_增加QA用的資料表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
